---
services:
  code-server:
    image: vscode-xp-workspace-deb10-arm64:0.8
    container_name: vscode-xp-workspace-arm-deb10
    environment:
      - LANG=C.UTF-8
      - LC_ALL=C.UTF-8
    ports:
      - "3505:8080"
    volumes:
      - ./data:/home/coder/data
      - ./.config:/home/coder/.config
      - ./local:/home/coder/.local/share/code-server
